#include "gflags/gflags.h"
#include "glog/logging.h"

#include <glob.h>
#include <iostream>

#include <opencv2/opencv.hpp>

#include "opencvhdfs.h"

#include "lines.h"
#include "undistort.h"

#include "version.h"

#define USAGE_MESSAGE "uses the unwrap matrix generated by lens_undistort and undistorts and image."

DEFINE_string(input, "", "Path of a picture to be undistorted");
DEFINE_string(input_hdf5, "", "Path of unwrapping matrix, generated by lens_undistort");


int main(int argc, char** argv )
{
	gflags::SetUsageMessage(USAGE_MESSAGE);
	gflags::SetVersionString(VERSION);

	gflags::ParseCommandLineFlags(&argc, &argv, true);
	google::InitGoogleLogging(argv[0]);

	

	cv::Mat unwrap_map;
	CVHDFS::read( FLAGS_input_hdf5, "map", unwrap_map);

	cv::Mat frame = cv::imread( FLAGS_input );
	cv::Mat unwraped;

	cv::remap(frame, unwraped, unwrap_map, cv::Mat(), cv::INTER_LANCZOS4);

	cv::imshow( "unwraped", unwraped );
	cv::waitKey(0);
}